name: Continuos Integration
on:
  workflow_dispatch:
    secrets:
      BRAINY_SERVER_REPOSITORY:
        required: true
      BRAINY_SERVER_REPOSITORY_SSH_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      branch:
        description: Branch name to build
        type: string
        required: true
        default: "main"
    
jobs:

  checkout:
    name: Checkout & checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up ssh agent
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
      - name: Checkout code
        shell: bash
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.BRAINY_SERVER_REPOSITORY_SSH_KEY }}" |  ssh-add -
          git clone ${{ secrets.BRAINY_SERVER_REPOSITORY }} .
          git checkout ${{ inputs.branch }}
          make clone_thirdparty_libs
      - name: Saving verified code
        uses: actions/upload-artifact@v4
        with:
          name: server-verified-code
          path: ./
          retention-days: 1

  build:
    name: Build
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          apt-get update && apt-get install -y build-essential make gettext gettext-base wget rsync git
          apt-get install -y libapr1-dev libaprutil1-dev libsqlite3-0 libsqlite3-dev sqlite3 libmysqlclient-dev libmysqlclient* libpq5 libpq-dev libssl-dev autoconf libtool zlib1g zlib1g-dev automake autotools-dev pkg-config libpng-dev libsdl1.2-dev libavahi-client-dev libavahi-common-dev libdbus-1-dev libmemcached-dev libcurl4-openssl-dev
          ln -s /usr/include/locale.h /usr/include/xlocale.h
          apt-get install -y cmake
          cmake -version

      - name: Retrieve verified code
        uses: actions/download-artifact@v4
        with:
          name: server-verified-code
          path: ./
      - name: Building
        run: |
          make skipTests=true build
      - name: Saving built code
        uses: actions/upload-artifact@v4
        with:
          name: server-built-code
          path: ./
          retention-days: 1

  unit-tests:
    name: Unit Test Suite
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve built code
        uses: actions/download-artifact@v4
        with:
          name: server-built-code
          path: ./
      - name: Building
        run: |
          make run-utests
