name: Build and Publish Brainy Server
on:
  workflow_dispatch:
    secrets:
      BRAINY_SERVER_REPOSITORY:
        required: true
      BRAINY_SERVER_REPOSITORY_SSH_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      branch:
        description: Branch name to build
        type: string
        required: true
        default: "main"
    
jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up ssh agent
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
      - name: Checkout code
        shell: bash
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.BRAINY_SERVER_REPOSITORY_SSH_KEY }}" |  ssh-add -
          git clone ${{ secrets.BRAINY_SERVER_REPOSITORY }} .
          git checkout ${{ inputs.branch }}
          ls -al

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debugging docker
        shell: bash
        run: |
          docker buildx ls; true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile.brainy
          platforms: linux/amd64, linux/arm64
          push: true
          tags: sjexpos/brainy:latest
